
spring:
  profiles:
    active: @profile.active@

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
  configuration:
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



